<?php return [
    'massMail' => 'Send Mass Mail',
    'shitMail' => 'Disposable Mail Domains',
    'shitMailAdd' => 'Add domain',
    'shitMailDelete' => 'Delete domain',
    'shitMailPrompt' => 'Enter domain or e-mail address',
    'shitMailConfirm' => 'Delete domain <b>{{domain}}</b> from the list?',
    'shitMailAdded' => 'Mail domain <b>{{domain}}</b> has been blocked',
    'liveStats' => 'Live Stats',
    'noActiveRooms' => 'No active rooms exist',
    'banUser' => 'Ban',
    'banUserConfirm' => 'Are you sure you want to ban <strong>{{name}}</strong>?',
    'banUserReason' => 'Ban reason (optional):',
    'broadcast' => 'Broadcast',
    'broadcastMessage' => 'Message to broadcast',
    'broadcastMessageModal' => 'Show in modal dialog',
    'viewLog' => 'View Messages Log',
    'viewLogDialog' => 'Last messages by {{name}}',
    'viewMailLogDialog' => 'Last PMs from {{sender}} to {{receiver}}',
];
