<?php return [
    'teamRoom' => 'Team',
    'blockPeriod' => 'Block period (minutes)',
    'blockPeriodHint' => 'Max: %d',
    'blockReason' => 'Block reason',
    'blockReasonHint' => 'Block reason will be visible for the user',
    'blockNotAllowed' => 'You cannot block this user',
    'reportsList' => 'Abuse Reports',
    'reportDate' => 'Created',
    'reportSuspect' => 'Suspect',
    'reportReporter' => 'Reported by',
    'reportReason' => 'Reason',
    'reportResult' => 'Status',
    'reportLog' => 'Chat Log',
    'reportLogMail' => 'PM Log',
    'reportProfile' => 'Profile',
    'reportText' => 'Report Text',
    'reportResultYes' => 'Resolved',
    'reportResultNo' => 'Pending',
    'reportResolution' => 'Report Resolution',
    'blockedTimes' => 'Blocked',
    'reportedTimes' => 'Reported',
    'ignoredTimes' => 'Ignored',
    'friendsCount' => 'Friends',
    'ipAddr' => 'IP',
    'userOldName' => 'Previous Name: %s',
];
